package xin.yuan.po;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.f_id
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.f_name
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.f_sex
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    private String fSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.f_accountid
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    private Integer fAccountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.f_id
     *
     * @return the value of friend.f_id
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.f_id
     *
     * @param fId the value for friend.f_id
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.f_name
     *
     * @return the value of friend.f_name
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.f_name
     *
     * @param fName the value for friend.f_name
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.f_sex
     *
     * @return the value of friend.f_sex
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public String getfSex() {
        return fSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.f_sex
     *
     * @param fSex the value for friend.f_sex
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public void setfSex(String fSex) {
        this.fSex = fSex == null ? null : fSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.f_accountid
     *
     * @return the value of friend.f_accountid
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public Integer getfAccountid() {
        return fAccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.f_accountid
     *
     * @param fAccountid the value for friend.f_accountid
     *
     * @mbg.generated Mon Mar 11 01:35:53 CST 2019
     */
    public void setfAccountid(Integer fAccountid) {
        this.fAccountid = fAccountid;
    }
}