package xin.yuan.entity;

import java.util.ArrayList;
import java.util.List;

public class FriendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public FriendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("f_id =", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("f_id >", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("f_id <", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdIn(List<Integer> values) {
            addCriterion("f_id in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFNameIsNull() {
            addCriterion("f_name is null");
            return (Criteria) this;
        }

        public Criteria andFNameIsNotNull() {
            addCriterion("f_name is not null");
            return (Criteria) this;
        }

        public Criteria andFNameEqualTo(String value) {
            addCriterion("f_name =", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotEqualTo(String value) {
            addCriterion("f_name <>", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThan(String value) {
            addCriterion("f_name >", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameGreaterThanOrEqualTo(String value) {
            addCriterion("f_name >=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThan(String value) {
            addCriterion("f_name <", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLessThanOrEqualTo(String value) {
            addCriterion("f_name <=", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameLike(String value) {
            addCriterion("f_name like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotLike(String value) {
            addCriterion("f_name not like", value, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameIn(List<String> values) {
            addCriterion("f_name in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotIn(List<String> values) {
            addCriterion("f_name not in", values, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameBetween(String value1, String value2) {
            addCriterion("f_name between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFNameNotBetween(String value1, String value2) {
            addCriterion("f_name not between", value1, value2, "fName");
            return (Criteria) this;
        }

        public Criteria andFSexIsNull() {
            addCriterion("f_sex is null");
            return (Criteria) this;
        }

        public Criteria andFSexIsNotNull() {
            addCriterion("f_sex is not null");
            return (Criteria) this;
        }

        public Criteria andFSexEqualTo(String value) {
            addCriterion("f_sex =", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexNotEqualTo(String value) {
            addCriterion("f_sex <>", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexGreaterThan(String value) {
            addCriterion("f_sex >", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexGreaterThanOrEqualTo(String value) {
            addCriterion("f_sex >=", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexLessThan(String value) {
            addCriterion("f_sex <", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexLessThanOrEqualTo(String value) {
            addCriterion("f_sex <=", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexLike(String value) {
            addCriterion("f_sex like", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexNotLike(String value) {
            addCriterion("f_sex not like", value, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexIn(List<String> values) {
            addCriterion("f_sex in", values, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexNotIn(List<String> values) {
            addCriterion("f_sex not in", values, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexBetween(String value1, String value2) {
            addCriterion("f_sex between", value1, value2, "fSex");
            return (Criteria) this;
        }

        public Criteria andFSexNotBetween(String value1, String value2) {
            addCriterion("f_sex not between", value1, value2, "fSex");
            return (Criteria) this;
        }

        public Criteria andFAccountidIsNull() {
            addCriterion("f_accountid is null");
            return (Criteria) this;
        }

        public Criteria andFAccountidIsNotNull() {
            addCriterion("f_accountid is not null");
            return (Criteria) this;
        }

        public Criteria andFAccountidEqualTo(Integer value) {
            addCriterion("f_accountid =", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidNotEqualTo(Integer value) {
            addCriterion("f_accountid <>", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidGreaterThan(Integer value) {
            addCriterion("f_accountid >", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_accountid >=", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidLessThan(Integer value) {
            addCriterion("f_accountid <", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidLessThanOrEqualTo(Integer value) {
            addCriterion("f_accountid <=", value, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidIn(List<Integer> values) {
            addCriterion("f_accountid in", values, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidNotIn(List<Integer> values) {
            addCriterion("f_accountid not in", values, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidBetween(Integer value1, Integer value2) {
            addCriterion("f_accountid between", value1, value2, "fAccountid");
            return (Criteria) this;
        }

        public Criteria andFAccountidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_accountid not between", value1, value2, "fAccountid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friend
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 11 01:52:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friend
     *
     * @mbg.generated Mon Mar 11 01:52:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}